---
- name: Get Installed Tower Version
  shell: /bin/tower-cli version | grep 'Ansible Tower' | awk '{print $3}'
  become: yes
  register: installed_tower_version_cmd
  failed_when: false

  # Install & Configure Tower CLI
- name: Install Pip
  become: true
  yum:
    name: python-pip

- name: Install tower-cli
  become: true
  pip:
    name: ansible-tower-cli

- name: Configure tower-cli
  become: true
  shell: tower-cli config --global host 127.0.0.1 && tower-cli config --global username admin && tower-cli config --global password {{ admin_password }}
  args:
    creates: /etc/tower/tower_cli.cfg

  # Install & Configure Tower
- name: Get Tower Install File
  unarchive:
    src: http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{ tower_version }}.tar.gz
    dest: /tmp
    remote_src: True
  when: installed_tower_version_cmd.stdout != tower_version

- name: Create inventory file, with setup passwords
  template:
    src: inventory.j2
    dest: /tmp/inventory
    mode: 0600
  when: installed_tower_version_cmd.stdout != tower_version

- name: Run Tower Setup Script
  become: true
  shell: ./setup.sh -i /tmp/inventory
  args:
    chdir: /tmp/ansible-tower-setup-{{ tower_version }}/
  when: installed_tower_version_cmd.stdout != tower_version

- name: Set tower Licence via tower-cli
  become: true
  shell: "tower-cli setting modify LICENSE '{{ license_data | to_json }}'"
